hosts = {
    'AD 93': 'AD93rec',
    'AMCO': 'mcosounds',
    'anu': 'noanunoparty',
    'Alexander Nut': 'AlexanderNut',
    'Aya': 'aya_yco',
    'Bladee': 'BladeeCity',
    'Blazer Sound System': 'BLAZER_SOUND',
    'Boom Bip': 'boombip',
    'Bradley Zero': 'bradleyzero',
    'Chantal Adams|Chantal': 'ChantalAdams',
    'Charlie Bones': 'D0YoU',
    'Dave ID': 'DaveIDmusic',
    'Delivery': 'DeliveryLA',
    'Death is not the End': 'deathisnot',
    'Eartheater': 'younggummystone',
    'Emotional Landscapes': 'maya_kal_',
    'Ernesto Chahoud': 'ernestchahoud',
    'Elena Colombi': 'ElenaColombi',
    'Flo': 'flollid',
    'Fractal Meat': 'grahamdunning',
    'From Sun City': 'from_sun_city',
    'Hesska': 'HesskaCITS',
    'House Call': 'HouseCallNts',
    'Huerco S[\.]*': 'huerco_s',
    'Moxie': 'DJMoxie',
    'Macca': 'maccalaaa',
    'Maria Somerville': 'mariasomerville',
    'Mark Leckey': 'MarkLeckey',
    'Motive': 'TheoMotive',
    'Nailah Hunter': 'nailah_hunter',
    'Naina': 'Naina_LDN',
    'Nedarb': 'nedarbnagrom',
    'Neoperreo': 'NEOPERREO_',
    'Optimo': 'JDTwitch',
    'Object Blue': 'objectblue_',
    'Oli XL': 'Oli_XL',
    'Post-geography': 'postgeography',
    '(?:Raji Rags|Raj Chaudhuri|Raj)': 'RajiRags',
    'Ruf Dug': 'RufDug',
    'Kevin Kusatsu': 'kevinkusatsu',
    'Kristin Kontrol': 'kristinkontrol',
    'Lee Gamble': 'GambleLee',
    'Light in the Attic': 'lightintheattic',
    'Lisha G': 'theonlyLishaG',
    'Louise Chen': 'CHCHCHEN_',
    'Mango Hell': 'mangohelll',
    'Minimal Wave': 'minimal_wave',
    'Miss Modular': 'missmodular_la',
    'Molinaro': 'moli_naro',
    'Nosedrip': 'Nosedrip',
    'Psychedelic Ensemble': 'ensemblepsych',
    'Radio Alhara': 'Radio_alHara',
    'Rhythm Section': 'rhythmsectionhq',
    'Ross Allen': 'rossallenmusic',
    'Scary Things': 'ScaryThingsLDN',
    '(?:Scratcha DVA|Scratcha)': 'ScratchaDVA',
    'Sherelle': 'iamsherelle',
    'Shy One': 'ShyOneBeats',
    'SKY H1': 'SKY_H1_',
    '(?:S K Y A P N E A|SKYAPNEA)': 'SKYAPNEA)',
    'SNO': 'DipItLowSNO',
    'Spirit Blue': '_sleepier_ & @TxImpey as @Spirit___Blue',
    'Tasker': 'NicTasker',
    'Total Stasis': 'Totalstasis',
    'Visible cloaks': 'visiblecloaks',
    'Yesterday[^\s]s news': 'hrricnelorraine',
    'Zakia': 'zakiasewell'
}