hosts = {
    'AD 93': 'AD93rec',
    'Air Max(?:.){0,1}97': 'xAirMax97x',
    'AMCO': 'mcosounds',
    'anu': 'noanunoparty',
    'Alexander Nut': 'AlexanderNut',
    'Andy Votel(?:.s){0,1}[s]*': 'AndyVotel',
    'Anz': 'yunganz_',
    'Aya': 'aya_yco',
    'Barnaby Bennett': 'BarnabyBennett',
    'Bergsonist': 'bergsonist',
    'Bladee': 'BladeeCity',
    'Blazer Sound System': 'BLAZER_SOUND',
    'Bokeh Versions': 'BokehVersions',
    'Boom Bip': 'boombip',
    'Body Motion': 'HelloBodyMotion',
    'Bradley Zero': 'bradleyzero',
    'Chantal Adams|Chantal': 'ChantalAdams',
    'Charlie Bones': 'D0YoU',
    'Circuits': 'circuits_nts',
    'Corin': 'CORIN_music',
    'Dave ID': 'DaveIDmusic',
    'Delivery': 'DeliveryLA',
    'Death is not the End': 'deathisnot',
    'DJ Bempah': 'DJ_Bempah',
    'DJ Nobu': 'dj_nobu_ft',
    'DJ Sundae': 'djsundae',
    'Eartheater': 'younggummystone',
    'Emotional Landscapes': 'maya_kal_',
    'Ernesto Chahoud': 'ernestchahoud',
    'Elena Colombi': 'ElenaColombi',
    '(?<!Auntie )(?<!Ambient )Flo': 'flollid',
    'Fractal Meat': 'grahamdunning',
    'From Sun City': 'from_sun_city',
    '(?:\()*Gost Zvuk(?:\)*)': 'gostzvuk',
    'Hesska': 'HesskaCITS',
    'House Call': 'HouseCallNts',
    'Huerco S[\.]*': 'huerco_s',
    'Jon Hopkins': 'Jon_Hopkins_',
    'JK': 'ScarythingsJK',
    'Kuunatic': 'kuunatic',
    'London Contemporary Orchestra': 'LCOrchestra',
    'Martha': 'MARTHAradio',
    'Moxie': 'DJMoxie',
    'Macca': 'maccalaaa',
    'Maria Somerville': 'mariasomerville',
    'Mark Leckey': 'MarkLeckey',
    'Meuko! Meuko!': 'meuko_meuko',
    'Motive': 'TheoMotive',
    'Nabihah Iqbal': 'nabihahiqbal',
    'Nailah Hunter': 'nailah_hunter',
    'Naina': 'Naina_LDN',
    'Nedarb': 'nedarbnagrom',
    'Neoperreo': 'NEOPERREO_',
    'Occo': 'occko',
    'Optimo': 'JDTwitch',
    'Object Blue': 'objectblue_',
    'Oli XL': 'Oli_XL',
    'Onra': 'ONRAbeats',
    'Post-geography': 'postgeography',
    '(?:Raji Rags|Raj Chaudhuri|Raj)': 'RajiRags',
    'Ruf Dug': 'RufDug',
    'Kevin Kusatsu': 'kevinkusatsu',
    'Kristin Kontrol': 'kristinkontrol',
    'Lee Gamble': 'GambleLee',
    'Light in the Attic': 'lightintheattic',
    'Lisha G': 'theonlyLishaG',
    'Louise Chen': 'CHCHCHEN_',
    'Mango Hell': 'mangohelll',
    'Minimal Wave': 'minimal_wave',
    'Miss Modular': 'missmodular_la',
    'Molinaro': 'moli_naro',
    'Nosedrip': 'Nosedrip',
    'Psychedelic Ensemble': 'ensemblepsych',
    'Radio Alhara': 'Radio_alHara',
    'Rhythm Section': 'rhythmsectionhq',
    'Ribeka': 'r_ibeka',
    'Ross Allen': 'rossallenmusic',
    'Scary Things': 'ScaryThingsLDN',
    '(?:Scratcha DVA|Scratcha)': 'ScratchaDVA',
    'Sherelle': 'iamsherelle',
    'Shy One': 'ShyOneBeats',
    'Skinny Girl Diet': 'skinnygirldiett',
    'SKY H1': 'SKY_H1_',
    '(?:S K Y A P N E A|SKYAPNEA)': 'SKYAPNEA)',
    'SNO': 'DipItLowSNO',
    'Sofay': 'ssofay',
    'Spirit Blue': '_sleepier_ & @TxImpey as @Spirit___Blue',
    'Tasker': 'NicTasker',
    'The Large': 'itsthelarge',
    'Tim (?:&|and) Barry': 'timandbarry',
    'Total Stasis': 'Totalstasis',
    'Yeaji': 'kraeji',
    'Visible cloaks': 'visiblecloaks',
    'Yesterday[^\s]s news': 'hrricnelorraine',
    'Yung Sherman': 'yung_sherman',
    'Zakia': 'zakiasewell'
}
