hosts = {
    'AD 93': 'AD93rec',
    'AMCO': 'mcosounds',
    'Alexander Nut': 'AlexanderNut',
    'Aya': 'aya_yco',
    'Bladee': 'BladeeCity',
    'Blazer Sound System': 'BLAZER_SOUND',
    'Boom Bip': 'boombip',
    'Charlie Bones': 'D0YoU',
    'Dave ID': 'DaveIDmusic',
    'Delivery': 'DeliveryLA',
    'Death is not the End': 'deathisnot',
    'Emotional Landscapes': 'maya_kal_',
    'Ernesto Chahoud': 'ernestchahoud',
    'Elena Colombi': 'ElenaColombi',
    'Flo': 'flollid',
    'Fractal Meat': 'grahamdunning',
    'House Call': 'HouseCallNts',
    'Moxie': 'DJMoxie',
    'Macca': 'maccalaaa',
    'Maria Somerville': 'ariasomerville',
    'Mark Leckey': 'MarkLeckey',
    'Nailah Hunter': 'nailah_hunter',
    'Naina': 'Naina_LDN',
    'Nedarb': 'nedarbnagrom',
    'Neoperreo': 'NEOPERREO_',
    'Optimo': 'JDTwitch',
    'Object Blue'
    '(?:Raji Rags|Raj Chaudhuri|Raj)': 'RajiRags',
    'Ruf Dug': 'RufDug',
    'Kevin Kusatsu': 'kevinkusatsu',
    'Kristin Kontrol': 'kristinkontrol',
    'Lee Gamble': 'GambleLee',
    'Light in the Attic': 'lightintheattic',
    'Lisha G': 'theonlyLishaG',
    'Louise Chen': 'CHCHCHEN_',
    'Psychedelic Ensemble': 'ensemblepsych',
    '(?:Scratcha DVA|Scratcha)': 'ScratchaDVA',
    'Sherelle': 'iamsherelle',
    'SKY H1': 'SKY_H1_',
    '(?:S K Y A P N E A|)': 'SKYAPNEA)',
    'Tasker': 'NicTasker',
    'Total Stasis': 'Totalstasis',
    'Death Is Not The End': 'deathisnot',
    'Zakia': 'zakiasewell'
}